// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRhSwUOKPxtSMX-_gQQ6Oq3s-y0-qOgY',
    appId: '1:83247428077:web:843a888b666923185477e4',
    messagingSenderId: '83247428077',
    projectId: 'single-obelisk-389301',
    authDomain: 'single-obelisk-389301.firebaseapp.com',
    storageBucket: 'single-obelisk-389301.appspot.com',
    measurementId: 'G-NG47803PZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU5AlIhju1ITqAU1oE7xQS4pUjHD1qjvY',
    appId: '1:83247428077:android:d302e5307ec4a0e75477e4',
    messagingSenderId: '83247428077',
    projectId: 'single-obelisk-389301',
    storageBucket: 'single-obelisk-389301.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRrC9XyNJzv_DXss-tJzj7No3j47kXIKA',
    appId: '1:83247428077:ios:5cfdaa8711c187f05477e4',
    messagingSenderId: '83247428077',
    projectId: 'single-obelisk-389301',
    storageBucket: 'single-obelisk-389301.appspot.com',
    androidClientId: '83247428077-c6tetj0ko92gj0t3s49o3qg21fl8v33f.apps.googleusercontent.com',
    iosClientId: '83247428077-v0otucnidhnla4jab0q9es5phkj1n09i.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkEv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRrC9XyNJzv_DXss-tJzj7No3j47kXIKA',
    appId: '1:83247428077:ios:c8b8892b3445fe335477e4',
    messagingSenderId: '83247428077',
    projectId: 'single-obelisk-389301',
    storageBucket: 'single-obelisk-389301.appspot.com',
    androidClientId: '83247428077-c6tetj0ko92gj0t3s49o3qg21fl8v33f.apps.googleusercontent.com',
    iosClientId: '83247428077-d0u5nlkbe6k922cv09ned3gfv53psdka.apps.googleusercontent.com',
    iosBundleId: 'com.example.sparkEv.RunnerTests',
  );
}
